### ISSUE TITLE
Hello?

### ISSUE THREAD

**Issue by filstorageok** [lk2684753/sd-cloud#2]
@lk2684753
한국 사람이죠?
sd-cloud 멎지네요.
소통 가능하실까요?

카톡 입니다.
https://open.kakao.com/o/snTCdgdd

**Comment by lk2684753** [comment]
> @lk2684753 한국 사람이죠? sd-cloud 멎지네요. 소통 가능하실까요?
> 
> 카톡 입니다. https://open.kakao.com/o/snTCdgdd

No, I'm not Korean. Sd-cloud works fine so far.
You can reach us on Telegram at https://t.me/+CqZWBUd3PTFlY2I1
